# Generated by Django 5.1.3 on 2024-11-24 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_student_created_at_student_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='courseId',
            new_name='course_Id',
        ),
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(upload_to='media/media/profile_pic'),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
