# Generated by Django 5.1.3 on 2024-12-02 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_staff_leave'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff_leave',
            old_name='date',
            new_name='data',
        ),
    ]
