# Generated by Django 5.1.3 on 2024-12-02 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_date_staff_leave_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_notification',
            name='status',
            field=models.ImageField(default=0, null=True, upload_to=''),
        ),
    ]
