# Generated by Django 5.1.3 on 2024-12-03 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_staff_notification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_notification',
            name='status',
            field=models.ImageField(default=0, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Staff_leave',
        ),
    ]
